[project]
name = "oarslily"
version = "0.1.3a13"
description = "Add your description here"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.13"
dependencies = [
    "osslili @ git+https://github.com/hfpg2026/osslili@b286c74a740c0162223c16c5518387c55c832af7",
    "python-levenshtein>=0.27.3",
    "python-tlsh>=4.5.0",
    "typer>=0.21.1",
]

[project.scripts]
oarslily = "oarslily.cli:app"

[tool.setuptools]
packages = ["oarslily", "oarslily.core"]

[tool.uv]
package = true